---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: akrzos-test
  name: akrzos-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: akrzos-test
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: akrzos-test
    spec:
      containers:
      - name: grafana
        image: docker.io/grafana/grafana:5.4.3
        ports:
        - name: grafana-http
          containerPort: 3000
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: akrzos-test-pvc
      volumes:
      - name: akrzos-test-pvc
        persistentVolumeClaim:
          claimName: akrzos-test-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: akrzos-test-svc
  labels:
    metrics-infra: systems-test
    name: akrzos-test-svc
spec:
  ports:
  - name: akrzos-test-svc
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: akrzos-test
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: akrzos-route-test
spec:
  to:
    name: akrzos-test-svc
  port:
    targetPort: 3000
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: akrzos-test-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: blue
  resources:
    requests:
      storage: 1Gi
